# Generated by Django 2.1.5 on 2019-01-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
